{{- if .Values.backend.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "iumbit.fullname" . }}-backend
  labels:
    {{- include "iumbit.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "iumbit.fullname" . }}-backend
  minReplicas: {{ .Values.backend.hpa.minReplicas }}
  maxReplicas: {{ .Values.backend.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.hpa.targetCPUUtilizationPercentage }}
    {{- if .Values.backend.hpa.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.backend.hpa.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.backend.hpa.behavior }}
  behavior:
    {{- toYaml .Values.backend.hpa.behavior | nindent 4 }}
  {{- end }}
{{- end }}
