apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tenant-provisioning.fullname" . }}-secrets
  labels:
    {{- include "tenant-provisioning.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  TENANTS_REPO_TOKEN: {{ .Values.secrets.tenantsRepoToken | b64enc | quote }}
  ARGOCD_TOKEN: {{ .Values.secrets.argocdToken | b64enc | quote }}
