apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "iumbit.fullname" . }}-config
  labels:
    {{- include "iumbit.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.config.serverPort | default "8080" | quote }}
  DB_HOST: {{ include "iumbit.fullname" . }}-postgresql
  DB_PORT: "5432"
  DB_NAME: {{ .Values.postgresql.auth.database | quote }}
  DB_URL: {{ .Values.config.dbUrl | quote }}
  CHECKIT_FRONT_REGISTER_VIEW: {{ .Values.config.checkitFrontRegisterView | quote }}
  VUE_APP_API_URL: {{ .Values.frontend.vueAppApiUrl | default "/check-it-1.0.0-dev.16/api/v1/" | quote }}
  VUE_CLI_TEST: {{ .Values.frontend.vueCliTest | default "true" | quote }}
  VUE_APP_GOOGLE_CLIENT_ID: {{ .Values.frontend.vueAppGoogleClientId | default "" | quote }}
  VUE_APP_MICROSOFT_CLIENT_ID: {{ .Values.frontend.vueAppMicrosoftClientId | default "" | quote }}
  VUE_APP_MICROSOFT_TENANT_ID: {{ .Values.frontend.vueAppMicrosoftTenantId | default "common" | quote }}
