apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iumbit.fullname" . }}-secrets
  labels:
    {{- include "iumbit.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.dbUsername | default "postgres" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | default "postgres" | b64enc | quote }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}
  GOOGLE_CLIENT_ID: {{ .Values.secrets.googleClientId | b64enc | quote }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | b64enc | quote }}
  MICROSOFT_CLIENT_ID: {{ .Values.secrets.microsoftClientId | b64enc | quote }}
  MICROSOFT_TENANT_ID: {{ .Values.secrets.microsoftTenantId | b64enc | quote }}
  MAIL_USERNAME: {{ .Values.secrets.mailUsername | b64enc | quote }}
  MAIL_PASSWORD: {{ .Values.secrets.mailPassword | b64enc | quote }}
