apiVersion: v1
kind: Service
metadata:
  name: {{ include "iumbit.fullname" . }}-frontend
  labels:
    {{- include "iumbit.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "iumbit.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
