apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "atom.fullname" . }}-proxy-config
  labels:
    {{- include "atom.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
data:
  Caddyfile: |
    :{{ .Values.proxy.port }} {
        log {
            output stdout
        }

        handle /core/* {
            header Set-Cookie ";Secure" ""
            header Set-Cookie "; Secure" ""
            uri replace /core/ /sicc/core/
            reverse_proxy {{ include "atom.fullname" . }}-backend:{{ .Values.backend.port }}
        }

        handle /wms/* {
            header Set-Cookie ";Secure" ""
            header Set-Cookie "; Secure" ""
            uri replace /wms/ /sicc-wms/wms/
            reverse_proxy {{ include "atom.fullname" . }}-backend:{{ .Values.backend.port }}
        }

        handle /pos/* {
            header Set-Cookie ";Secure" ""
            header Set-Cookie "; Secure" ""
            uri replace /pos/ /sicc-pos/pos/
            reverse_proxy {{ include "atom.fullname" . }}-backend:{{ .Values.backend.port }}
        }

        handle /api/* {
            header Set-Cookie ";Secure" ""
            header Set-Cookie "; Secure" ""
            reverse_proxy {{ include "atom.fullname" . }}-backend:{{ .Values.backend.port }}
        }

        handle {
            reverse_proxy {{ include "atom.fullname" . }}-frontend:{{ .Values.frontend.port }}
        }
    }
