apiVersion: v1
kind: Service
metadata:
  name: {{ include "atom.fullname" . }}-proxy
  labels:
    {{- include "atom.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  type: NodePort
  ports:
    - port: {{ .Values.proxy.port }}
      targetPort: {{ .Values.proxy.port }}
      nodePort: {{ .Values.proxy.nodePort }}
      protocol: TCP
      name: http
  selector:
    {{- include "atom.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
