global:
  environment: qa

postgresql:
  primary:
    persistence:
      size: 20Gi
    resources:
      requests:
        cpu: 500m
        memory: 1Gi

backend:
  replicas: 2
  hpa:
    enabled: false

frontend:
  replicas: 2
  hpa:
    enabled: false

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: iumbit-qa.local
      paths:
        - path: /
          pathType: Prefix
          serviceName: frontend
          servicePort: 8080
        - path: /check-it-1.0.0-dev.16
          pathType: Prefix
          serviceName: backend
          servicePort: 8080
