global:
  environment: staging

postgresql:
  primary:
    persistence:
      size: 30Gi
    resources:
      requests:
        cpu: "1"
        memory: 2Gi

backend:
  replicas: 2
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80

frontend:
  replicas: 2
  hpa:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: iumbit-staging.local
      paths:
        - path: /
          pathType: Prefix
          serviceName: frontend
          servicePort: 8080
        - path: /check-it-1.0.0-dev.16
          pathType: Prefix
          serviceName: backend
          servicePort: 8080
