apiVersion: v1
kind: Secret
metadata:
  name: {{ include "atom.fullname" . }}-secrets
  labels:
    {{- include "atom.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
type: Opaque
data:
  DB_USERNAME: {{ .Values.secrets.dbUsername | default "postgres" | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | default "postgres" | b64enc | quote }}
